steps:
  - name: 'google/cloud-sdk:latest'
    args:
      - '-c'
      - |-
        
        set -eo pipefail
        
        gcloud source repos clone test-csr3 csr_code --project=dbk-sre-streamingapi-1575
        
        cd csr_code/
        git checkout master
        git pull origin master
        branch=$(date '+%Y%m%d%H%M%S')
        git checkout -b $branch
        cd ..
        
        cp -r /workspace/!(csr_code) /workspace/csr_code/
        cd /workspace/csr_code/
        
        git config --global user.name "Cloud Build"
        git config --global user.email "813015284617@cloudbuild.gserviceaccount.com"
        git add .
        git commit -m "Master branch copied"
        git push
        echo "Copied GIT code to Cloud Source Repo"  

    entrypoint: bash
substitutions:
  _PROJECT_ID: dbk-sre-streamingapi-1575
  _TOKEN: dsds
  _TARGET_REPO: JA250514/test_repo1
