steps:
  - name: 'google/cloud-sdk:latest'
    args:
      - '-c'
      - |-
        
        set -eo pipefail
        echo "Calling Looker APIs."
        looker_token=$(curl --request POST 'https://ncredsdev.cloud.looker.com/api/4.0/login?client_id=RhHYhp2yQhpFkWDP2MRJ&client_secret=vbzH7PQjBCtfXcYsnDJbTyyg' | sed -e 's/{"access_token":"\(.*\)","token_type.*/\1/')
        echo $looker_token
        curl --request POST 'https://ncredsdev.cloud.looker.com/api/4.0/projects/eds/deploy_ref_to_production?branch' --header "Authorization: Bearer $looker_token"
        echo "Looker APIs calls are successfully finished."  

    entrypoint: bash
substitutions:

